package com.example.sunxu_mall.mapper.mall;

import com.example.sunxu_mall.entity.mall.AttributeValueEntity;
import com.example.sunxu_mall.entity.mall.AttributeValueEntityExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface AttributeValueEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_attribute_value
     *
     * @mbg.generated
     */
    long countByExample(AttributeValueEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_attribute_value
     *
     * @mbg.generated
     */
    int deleteByExample(AttributeValueEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_attribute_value
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_attribute_value
     *
     * @mbg.generated
     */
    int insert(AttributeValueEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_attribute_value
     *
     * @mbg.generated
     */
    int insertSelective(AttributeValueEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_attribute_value
     *
     * @mbg.generated
     */
    List<AttributeValueEntity> selectByExample(AttributeValueEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_attribute_value
     *
     * @mbg.generated
     */
    AttributeValueEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_attribute_value
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") AttributeValueEntity row, @Param("example") AttributeValueEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_attribute_value
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") AttributeValueEntity row, @Param("example") AttributeValueEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_attribute_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AttributeValueEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_attribute_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AttributeValueEntity row);
}