package com.example.sunxu_mall.mapper.mall;

import com.example.sunxu_mall.entity.mall.CommonPhotoEntity;
import com.example.sunxu_mall.entity.mall.CommonPhotoEntityExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface CommonPhotoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_photo
     *
     * @mbg.generated
     */
    long countByExample(CommonPhotoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_photo
     *
     * @mbg.generated
     */
    int deleteByExample(CommonPhotoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_photo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_photo
     *
     * @mbg.generated
     */
    int insert(CommonPhotoEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_photo
     *
     * @mbg.generated
     */
    int insertSelective(CommonPhotoEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_photo
     *
     * @mbg.generated
     */
    List<CommonPhotoEntity> selectByExample(CommonPhotoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_photo
     *
     * @mbg.generated
     */
    CommonPhotoEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_photo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") CommonPhotoEntity row, @Param("example") CommonPhotoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_photo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") CommonPhotoEntity row, @Param("example") CommonPhotoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_photo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CommonPhotoEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_photo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CommonPhotoEntity row);
}