package com.example.sunxu_mall.mapper.mall;

import com.example.sunxu_mall.entity.mall.MallProductFavoritesEntity;
import com.example.sunxu_mall.entity.mall.MallProductFavoritesEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MallProductFavoritesEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_favorites
     *
     * @mbg.generated
     */
    long countByExample(MallProductFavoritesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_favorites
     *
     * @mbg.generated
     */
    int deleteByExample(MallProductFavoritesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_favorites
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_favorites
     *
     * @mbg.generated
     */
    int insert(MallProductFavoritesEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_favorites
     *
     * @mbg.generated
     */
    int insertSelective(MallProductFavoritesEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_favorites
     *
     * @mbg.generated
     */
    List<MallProductFavoritesEntity> selectByExample(MallProductFavoritesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_favorites
     *
     * @mbg.generated
     */
    MallProductFavoritesEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_favorites
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") MallProductFavoritesEntity row, @Param("example") MallProductFavoritesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_favorites
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") MallProductFavoritesEntity row, @Param("example") MallProductFavoritesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_favorites
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MallProductFavoritesEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_favorites
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MallProductFavoritesEntity row);
}