package com.example.sunxu_mall.mapper.mall;

import com.example.sunxu_mall.entity.mall.MallUnitEntity;
import com.example.sunxu_mall.entity.mall.MallUnitEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MallUnitEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_unit
     *
     * @mbg.generated
     */
    long countByExample(MallUnitEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_unit
     *
     * @mbg.generated
     */
    int deleteByExample(MallUnitEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_unit
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_unit
     *
     * @mbg.generated
     */
    int insert(MallUnitEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_unit
     *
     * @mbg.generated
     */
    int insertSelective(MallUnitEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_unit
     *
     * @mbg.generated
     */
    List<MallUnitEntity> selectByExample(MallUnitEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_unit
     *
     * @mbg.generated
     */
    MallUnitEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_unit
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") MallUnitEntity row, @Param("example") MallUnitEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_unit
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") MallUnitEntity row, @Param("example") MallUnitEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_unit
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MallUnitEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_unit
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MallUnitEntity row);
}