package com.example.sunxu_mall.mapper.mall;

import com.example.sunxu_mall.entity.mall.MallAttributeValueEntity;
import com.example.sunxu_mall.entity.mall.MallAttributeValueEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MallAttributeValueEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_attribute_value
     *
     * @mbg.generated
     */
    long countByExample(MallAttributeValueEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_attribute_value
     *
     * @mbg.generated
     */
    int deleteByExample(MallAttributeValueEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_attribute_value
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_attribute_value
     *
     * @mbg.generated
     */
    int insert(MallAttributeValueEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_attribute_value
     *
     * @mbg.generated
     */
    int insertSelective(MallAttributeValueEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_attribute_value
     *
     * @mbg.generated
     */
    List<MallAttributeValueEntity> selectByExample(MallAttributeValueEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_attribute_value
     *
     * @mbg.generated
     */
    MallAttributeValueEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_attribute_value
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") MallAttributeValueEntity row, @Param("example") MallAttributeValueEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_attribute_value
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") MallAttributeValueEntity row, @Param("example") MallAttributeValueEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_attribute_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MallAttributeValueEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_attribute_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MallAttributeValueEntity row);

    /**
     * 带 limit 的列表查询（用于导出等场景）
     */
    List<com.example.sunxu_mall.vo.mall.AttributeValueVO> selectListWithLimit(
            @Param("attributeId") Long attributeId,
            @Param("value") String value,
            @Param("limit") int limit
    );

    /**
     * 带 limit 的游标分页查询
     */
    List<com.example.sunxu_mall.vo.mall.AttributeValueVO> selectByCursorWithLimit(
            @Param("attributeId") Long attributeId,
            @Param("value") String value,
            @Param("cursorId") Long cursorId,
            @Param("limit") int limit
    );
}