package com.example.sunxu_mall.mapper.mall;

import com.example.sunxu_mall.entity.mall.MallBrandEntity;
import com.example.sunxu_mall.entity.mall.MallBrandEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MallBrandEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_brand
     *
     * @mbg.generated
     */
    long countByExample(MallBrandEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_brand
     *
     * @mbg.generated
     */
    int deleteByExample(MallBrandEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_brand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_brand
     *
     * @mbg.generated
     */
    int insert(MallBrandEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_brand
     *
     * @mbg.generated
     */
    int insertSelective(MallBrandEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_brand
     *
     * @mbg.generated
     */
    List<MallBrandEntity> selectByExample(MallBrandEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_brand
     *
     * @mbg.generated
     */
    MallBrandEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_brand
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") MallBrandEntity row, @Param("example") MallBrandEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_brand
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") MallBrandEntity row, @Param("example") MallBrandEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MallBrandEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MallBrandEntity row);
}