package com.example.sunxu_mall.mapper.mall;

import com.example.sunxu_mall.entity.mall.MallProductCommentEntity;
import com.example.sunxu_mall.entity.mall.MallProductCommentEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MallProductCommentEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_comment
     *
     * @mbg.generated
     */
    long countByExample(MallProductCommentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_comment
     *
     * @mbg.generated
     */
    int deleteByExample(MallProductCommentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_comment
     *
     * @mbg.generated
     */
    int insert(MallProductCommentEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_comment
     *
     * @mbg.generated
     */
    int insertSelective(MallProductCommentEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_comment
     *
     * @mbg.generated
     */
    List<MallProductCommentEntity> selectByExample(MallProductCommentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_comment
     *
     * @mbg.generated
     */
    MallProductCommentEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_comment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") MallProductCommentEntity row, @Param("example") MallProductCommentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_comment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") MallProductCommentEntity row, @Param("example") MallProductCommentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MallProductCommentEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MallProductCommentEntity row);
}