package com.example.sunxu_mall.mapper.mall;

import com.example.sunxu_mall.entity.mall.MallProductGroupEntity;
import com.example.sunxu_mall.entity.mall.MallProductGroupEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MallProductGroupEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_group
     *
     * @mbg.generated
     */
    long countByExample(MallProductGroupEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_group
     *
     * @mbg.generated
     */
    int deleteByExample(MallProductGroupEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_group
     *
     * @mbg.generated
     */
    int insert(MallProductGroupEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_group
     *
     * @mbg.generated
     */
    int insertSelective(MallProductGroupEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_group
     *
     * @mbg.generated
     */
    List<MallProductGroupEntity> selectByExample(MallProductGroupEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_group
     *
     * @mbg.generated
     */
    MallProductGroupEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_group
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") MallProductGroupEntity row, @Param("example") MallProductGroupEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_group
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") MallProductGroupEntity row, @Param("example") MallProductGroupEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MallProductGroupEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MallProductGroupEntity row);
}