package com.example.sunxu_mall.mapper.mall;

import com.example.sunxu_mall.entity.mall.MallProductDetailEntity;
import com.example.sunxu_mall.entity.mall.MallProductDetailEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MallProductDetailEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_detail
     *
     * @mbg.generated
     */
    long countByExample(MallProductDetailEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_detail
     *
     * @mbg.generated
     */
    int deleteByExample(MallProductDetailEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_detail
     *
     * @mbg.generated
     */
    int insert(MallProductDetailEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_detail
     *
     * @mbg.generated
     */
    int insertSelective(MallProductDetailEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_detail
     *
     * @mbg.generated
     */
    List<MallProductDetailEntity> selectByExampleWithBLOBs(MallProductDetailEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_detail
     *
     * @mbg.generated
     */
    List<MallProductDetailEntity> selectByExample(MallProductDetailEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_detail
     *
     * @mbg.generated
     */
    MallProductDetailEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_detail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") MallProductDetailEntity row, @Param("example") MallProductDetailEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_detail
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") MallProductDetailEntity row, @Param("example") MallProductDetailEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_detail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") MallProductDetailEntity row, @Param("example") MallProductDetailEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MallProductDetailEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(MallProductDetailEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MallProductDetailEntity row);
}