package com.example.sunxu_mall.mapper.mall;

import com.example.sunxu_mall.entity.mall.MallCategoryEntity;
import com.example.sunxu_mall.entity.mall.MallCategoryEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MallCategoryEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_category
     *
     * @mbg.generated
     */
    long countByExample(MallCategoryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_category
     *
     * @mbg.generated
     */
    int deleteByExample(MallCategoryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_category
     *
     * @mbg.generated
     */
    int insert(MallCategoryEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_category
     *
     * @mbg.generated
     */
    int insertSelective(MallCategoryEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_category
     *
     * @mbg.generated
     */
    List<MallCategoryEntity> selectByExample(MallCategoryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_category
     *
     * @mbg.generated
     */
    MallCategoryEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") MallCategoryEntity row, @Param("example") MallCategoryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") MallCategoryEntity row, @Param("example") MallCategoryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MallCategoryEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MallCategoryEntity row);
}