package com.example.sunxu_mall.mapper.mall;

import com.example.sunxu_mall.entity.mall.MallAttributeEntity;
import com.example.sunxu_mall.entity.mall.MallAttributeEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MallAttributeEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_attribute
     *
     * @mbg.generated
     */
    long countByExample(MallAttributeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_attribute
     *
     * @mbg.generated
     */
    int deleteByExample(MallAttributeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_attribute
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_attribute
     *
     * @mbg.generated
     */
    int insert(MallAttributeEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_attribute
     *
     * @mbg.generated
     */
    int insertSelective(MallAttributeEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_attribute
     *
     * @mbg.generated
     */
    List<MallAttributeEntity> selectByExample(MallAttributeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_attribute
     *
     * @mbg.generated
     */
    MallAttributeEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_attribute
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") MallAttributeEntity row, @Param("example") MallAttributeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_attribute
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") MallAttributeEntity row, @Param("example") MallAttributeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MallAttributeEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MallAttributeEntity row);
}