package com.example.sunxu_mall.mapper.mall;

import com.example.sunxu_mall.entity.mall.MallProductPhotoEntity;
import com.example.sunxu_mall.entity.mall.MallProductPhotoEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MallProductPhotoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_photo
     *
     * @mbg.generated
     */
    long countByExample(MallProductPhotoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_photo
     *
     * @mbg.generated
     */
    int deleteByExample(MallProductPhotoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_photo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_photo
     *
     * @mbg.generated
     */
    int insert(MallProductPhotoEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_photo
     *
     * @mbg.generated
     */
    int insertSelective(MallProductPhotoEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_photo
     *
     * @mbg.generated
     */
    List<MallProductPhotoEntity> selectByExample(MallProductPhotoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_photo
     *
     * @mbg.generated
     */
    MallProductPhotoEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_photo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") MallProductPhotoEntity row, @Param("example") MallProductPhotoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_photo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") MallProductPhotoEntity row, @Param("example") MallProductPhotoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_photo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MallProductPhotoEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_photo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MallProductPhotoEntity row);
}