package com.example.sunxu_mall.mapper.mall;

import com.example.sunxu_mall.entity.mall.ProductAttributeEntity;
import com.example.sunxu_mall.entity.mall.ProductAttributeEntityExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface ProductAttributeEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_attribute
     *
     * @mbg.generated
     */
    long countByExample(ProductAttributeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_attribute
     *
     * @mbg.generated
     */
    int deleteByExample(ProductAttributeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_attribute
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_attribute
     *
     * @mbg.generated
     */
    int insert(ProductAttributeEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_attribute
     *
     * @mbg.generated
     */
    int insertSelective(ProductAttributeEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_attribute
     *
     * @mbg.generated
     */
    List<ProductAttributeEntity> selectByExample(ProductAttributeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_attribute
     *
     * @mbg.generated
     */
    ProductAttributeEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_attribute
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") ProductAttributeEntity row, @Param("example") ProductAttributeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_attribute
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") ProductAttributeEntity row, @Param("example") ProductAttributeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductAttributeEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductAttributeEntity row);

    // ==================== 自定义方法（用于差量更新） ====================

    /**
     * 根据商品ID查询未删除的属性列表
     *
     * @param productId 商品ID
     * @return 属性列表
     */
    List<ProductAttributeEntity> selectByProductId(@Param("productId") Long productId);

    /**
     * 批量插入属性
     *
     * @param list 属性列表
     * @return 插入行数
     */
    int batchInsert(@Param("list") List<ProductAttributeEntity> list);

    /**
     * 批量软删除指定ID的属性
     *
     * @param ids           属性ID列表
     * @param updateUserId  更新用户ID
     * @param updateUserName 更新用户名
     * @return 更新行数
     */
    int batchSoftDeleteByIds(@Param("ids") List<Long> ids,
                              @Param("updateUserId") Long updateUserId,
                              @Param("updateUserName") String updateUserName);
}