package com.example.sunxu_mall.mapper.mall;

import com.example.sunxu_mall.entity.mall.ProductEntity;
import com.example.sunxu_mall.entity.mall.ProductEntityExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface ProductEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product
     *
     * @mbg.generated
     */
    long countByExample(ProductEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product
     *
     * @mbg.generated
     */
    int deleteByExample(ProductEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product
     *
     * @mbg.generated
     */
    int insert(ProductEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product
     *
     * @mbg.generated
     */
    int insertSelective(ProductEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product
     *
     * @mbg.generated
     */
    List<ProductEntity> selectByExample(ProductEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product
     *
     * @mbg.generated
     */
    ProductEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") ProductEntity row, @Param("example") ProductEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") ProductEntity row, @Param("example") ProductEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductEntity row);

    int updateProductInfoWithVersion(ProductEntity row);

    /**
     * 带 limit 的列表查询（用于导出等场景）
     */
    List<ProductEntity> selectListWithLimit(
            @Param("name") String name,
            @Param("model") String model,
            @Param("categoryId") Long categoryId,
            @Param("brandId") Long brandId,
            @Param("productGroupId") Long productGroupId,
            @Param("limit") int limit
    );

    /**
     * 带 limit 的游标分页查询
     */
    List<ProductEntity> selectByCursorWithLimit(
            @Param("name") String name,
            @Param("model") String model,
            @Param("categoryId") Long categoryId,
            @Param("brandId") Long brandId,
            @Param("productGroupId") Long productGroupId,
            @Param("cursorId") Long cursorId,
            @Param("limit") int limit
    );
}