package com.example.sunxu_mall.mapper.mall;

import com.example.sunxu_mall.entity.mall.ProductGroupAttributeEntity;
import com.example.sunxu_mall.entity.mall.ProductGroupAttributeEntityExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface ProductGroupAttributeEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_group_attribute
     *
     * @mbg.generated
     */
    long countByExample(ProductGroupAttributeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_group_attribute
     *
     * @mbg.generated
     */
    int deleteByExample(ProductGroupAttributeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_group_attribute
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_group_attribute
     *
     * @mbg.generated
     */
    int insert(ProductGroupAttributeEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_group_attribute
     *
     * @mbg.generated
     */
    int insertSelective(ProductGroupAttributeEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_group_attribute
     *
     * @mbg.generated
     */
    List<ProductGroupAttributeEntity> selectByExample(ProductGroupAttributeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_group_attribute
     *
     * @mbg.generated
     */
    ProductGroupAttributeEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_group_attribute
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") ProductGroupAttributeEntity row, @Param("example") ProductGroupAttributeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_group_attribute
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") ProductGroupAttributeEntity row, @Param("example") ProductGroupAttributeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_group_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductGroupAttributeEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_group_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductGroupAttributeEntity row);
}