package com.example.sunxu_mall.mapper.mall;

import com.example.sunxu_mall.entity.mall.ProductAttributeEntity;
import com.example.sunxu_mall.entity.mall.ProductAttributeEntityExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface ProductAttributeEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_attribute
     *
     * @mbg.generated
     */
    long countByExample(ProductAttributeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_attribute
     *
     * @mbg.generated
     */
    int deleteByExample(ProductAttributeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_attribute
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_attribute
     *
     * @mbg.generated
     */
    int insert(ProductAttributeEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_attribute
     *
     * @mbg.generated
     */
    int insertSelective(ProductAttributeEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_attribute
     *
     * @mbg.generated
     */
    List<ProductAttributeEntity> selectByExample(ProductAttributeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_attribute
     *
     * @mbg.generated
     */
    ProductAttributeEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_attribute
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") ProductAttributeEntity row, @Param("example") ProductAttributeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_attribute
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") ProductAttributeEntity row, @Param("example") ProductAttributeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductAttributeEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductAttributeEntity row);
}