package com.example.sunxu_mall.mapper.sys;

import com.example.sunxu_mall.entity.sys.web.UserWebEntity;
import com.example.sunxu_mall.entity.sys.web.UserWebEntityExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Update;

@Mapper
public interface UserWebEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    long countByExample(UserWebEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    int deleteByExample(UserWebEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    int insert(UserWebEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    int insertSelective(UserWebEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    List<UserWebEntity> selectByExample(UserWebEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    UserWebEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") UserWebEntity row, @Param("example") UserWebEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") UserWebEntity row, @Param("example") UserWebEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserWebEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserWebEntity row);

    UserWebEntity findByUserName(String userName);

    Integer selectVersionById(Long id);

    int updateUserInfoWithVersion(UserWebEntity row);

    /**
     * 带 limit 的列表查询（用于导出等场景）
     */
    List<UserWebEntity> selectListWithLimit(
            @Param("userName") String userName,
            @Param("phone") String phone,
            @Param("email") String email,
            @Param("validStatus") Boolean validStatus,
            @Param("deptId") Long deptId,
            @Param("limit") int limit
    );

    /**
     * 带 limit 的游标分页查询
     */
    List<UserWebEntity> selectByCursorWithLimit(
            @Param("userName") String userName,
            @Param("phone") String phone,
            @Param("email") String email,
            @Param("validStatus") Boolean validStatus,
            @Param("deptId") Long deptId,
            @Param("cursorId") Long cursorId,
            @Param("limit") int limit
    );
}
