package com.example.sunxu_mall.mapper.common;

import com.example.sunxu_mall.entity.common.CommonTaskEntity;
import com.example.sunxu_mall.entity.common.CommonTaskEntityExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CommonTaskEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    long countByExample(CommonTaskEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    int deleteByExample(CommonTaskEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    int insert(CommonTaskEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    int insertSelective(CommonTaskEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    List<CommonTaskEntity> selectByExampleWithBLOBs(CommonTaskEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    List<CommonTaskEntity> selectByExample(CommonTaskEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    CommonTaskEntity selectByPrimaryKey(Long id);

    /**
     * 根据业务键查询
     *
     * @param bizKey 业务键
     * @return 任务实体
     */
    CommonTaskEntity selectByBizKey(@Param("bizKey") String bizKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") CommonTaskEntity row, @Param("example") CommonTaskEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") CommonTaskEntity row, @Param("example") CommonTaskEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") CommonTaskEntity row, @Param("example") CommonTaskEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CommonTaskEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(CommonTaskEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CommonTaskEntity row);

    int updateTaskWithVersion(CommonTaskEntity row);

    /**
     * 根据幂等去重 Key 查询任务
     *
     * @param dedupKey 幂等去重 Key
     * @return 任务实体（含 BLOB 字段）
     */
    CommonTaskEntity selectByDedupKey(@Param("dedupKey") String dedupKey);

    /**
     * 查询进行中的同指纹任务（WAITING/RUNNING）
     *
     * @param fingerprint 任务参数指纹
     * @return 任务实体（含 BLOB 字段）
     */
    CommonTaskEntity selectInFlightByFingerprint(@Param("fingerprint") String fingerprint);

    /**
     * 原子抢占任务执行权：将 status 从 WAITING(0) 改为 RUNNING(1)
     * 用于消费端防重复执行
     *
     * @param bizKey 业务键
     * @return 影响行数，1=抢占成功，0=已被抢占或状态不对
     */
    int tryLockForRunByBizKey(@Param("bizKey") String bizKey);
}