package com.example.sunxu_mall.mapper.common;

import com.example.sunxu_mall.entity.common.CommonTaskEntity;
import com.example.sunxu_mall.entity.common.CommonTaskEntityExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CommonTaskEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    long countByExample(CommonTaskEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    int deleteByExample(CommonTaskEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    int insert(CommonTaskEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    int insertSelective(CommonTaskEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    List<CommonTaskEntity> selectByExampleWithBLOBs(CommonTaskEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    List<CommonTaskEntity> selectByExample(CommonTaskEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    CommonTaskEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") CommonTaskEntity row, @Param("example") CommonTaskEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") CommonTaskEntity row, @Param("example") CommonTaskEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") CommonTaskEntity row, @Param("example") CommonTaskEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CommonTaskEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(CommonTaskEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CommonTaskEntity row);

    int updateTaskWithVersion(CommonTaskEntity row);
}