package com.example.sunxu_mall.mapper.common;

import com.example.sunxu_mall.entity.common.CommonNotifyEntity;
import com.example.sunxu_mall.entity.common.CommonNotifyEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommonNotifyEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_notify
     *
     * @mbg.generated
     */
    long countByExample(CommonNotifyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_notify
     *
     * @mbg.generated
     */
    int deleteByExample(CommonNotifyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_notify
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_notify
     *
     * @mbg.generated
     */
    int insert(CommonNotifyEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_notify
     *
     * @mbg.generated
     */
    int insertSelective(CommonNotifyEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_notify
     *
     * @mbg.generated
     */
    List<CommonNotifyEntity> selectByExample(CommonNotifyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_notify
     *
     * @mbg.generated
     */
    CommonNotifyEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_notify
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") CommonNotifyEntity row, @Param("example") CommonNotifyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_notify
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") CommonNotifyEntity row, @Param("example") CommonNotifyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_notify
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CommonNotifyEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_notify
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CommonNotifyEntity row);

    int updateNotifyWithVersion(CommonNotifyEntity row);
}